spring:
    data:
        mongodb:
            host: 192.168.1.205
            port: 27017
            username: tqhy
            password: tqhy817
            database: ip_doc
            authentication-database: admin

